### ISSUE TITLE
working of your app.

### ISSUE THREAD

**Issue by tarsh98** [adhenrique/react-native-redux-thunk-authentication-example#1]
What exactly is the working of your app.
is it like after pressing the acessar button it goes to another screen if it's authorized and then we can press logout button to go back to the previous page.

**Comment by adhenrique** [comment]
@tarsh98 that's it!

**Comment by adhenrique** [comment]
@tarsh98 i need to update the Readme with more specific details about this repo. Sorry about this.

**Comment by tarsh98** [comment]
@adhenrique Thank you!
